### ISSUE TITLE
Remove the limitation of #eb5424 color to be used in contribution

### ISSUE THREAD

**Issue by faisal00813** [auth0/identicons#7]
## Request
Can you please remove the mandatory usage of color #eb5424 in all the contributions? 

## Why
Other organizations may find it inconvenient to use the orange color if it's not present in their company color palette.

## Alternative
To maintain consistency, it can be asked of the contributor who is introducing a new color instead of #eb5424, to have all the icons present in the new color also.
It might be required to introduce a new folder alongside dark and light folders to better organize the icons.

**Comment by Sambego** [comment]
Thanks for your feedback, for now we will not allow other colors.
